# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='beds_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='beds_total',
            field=models.IntegerField(null=True),
        ),
    ]
