# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_auto_20160526_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='person_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='person_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='shelter_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
